const DIAGRAM_ELEMENTS = {
  diagramId: 'c6aeac72-097a-482c-8610-83a052635c06',
  elements: {
    diagramNodes: [
      {
        id: 'nodeId_RpYfXKW7ArGsp8Mp36f1h',
        data: {
          id: 'nodeId_RpYfXKW7ArGsp8Mp36f1h',
          name: 'Start server',
          type: 'Start',
          label: '',
          style: {
            textStyles: {
              zIndex: 10,
              fontSize: 14,
              fontAlign: 'center',
              fontColor: '#4D4D4D',
              fontFamily: 'Roboto',
              fontStyles: [],
            },
            borderColor: '#000',
            borderWidth: 1,
          },
          isExecuted: false,
          elementType: 'Node',
          isCollapsed: true,
          connectedNodes: [],
        },
        type: 'Start',
        width: 35,
        height: 34,
        dragging: false,
        position: {
          x: -107.5,
          y: 23.5,
        },
        selected: false,
        positionAbsolute: {
          x: -107.5,
          y: 23.5,
        },
      },
      {
        id: 'nodeId_59vnYFC8qwH6NHUQriL_h',
        data: {
          id: 'nodeId_59vnYFC8qwH6NHUQriL_h',
          name: 'node name nodeId_59vnYFC8qwH6NHUQriL_h',
          type: 'Sink',
          label: '',
          style: {
            textStyles: {
              zIndex: 10,
              fontSize: 14,
              fontAlign: 'center',
              fontColor: '#4D4D4D',
              fontFamily: 'Roboto',
              fontStyles: [],
            },
            borderColor: '#000',
            borderWidth: 1,
          },
          history: [],
          trigger: {
            mode: 'automatic',
          },
          actionMode: 'pullAny',
          isExecuted: false,
          elementType: 'Node',
          isCollapsed: true,
          connectedNodes: [],
        },
        type: 'Sink',
        width: 116,
        height: 117,
        position: {
          x: 126.81965195659846,
          y: 11.824168106072433,
        },
      },
      {
        id: 'nodeId_4l51NxW5F8dxMFb1MRV1v',
        data: {
          id: 'nodeId_4l51NxW5F8dxMFb1MRV1v',
          name: 'MicroLoop',
          type: 'MicroLoop',
          label: '',
          style: {
            width: 300,
            height: 300,
            textStyles: {
              zIndex: 10,
              fontSize: 14,
              fontAlign: 'center',
              fontColor: '#4D4D4D',
              fontFamily: 'Roboto',
              fontStyles: [],
            },
            borderColor: '#000',
            borderWidth: 1,
          },
          children: [],
          isExecuted: false,
          elementType: 'Node',
          isCollapsed: true,
          connectedNodes: [],
          currentLoopCount: 0,
          incomingVariables: [],
          outgoingVariables: [],
        },
        type: 'MicroLoop',
        width: 145,
        height: 89,
        position: {
          x: 120.72579801352559,
          y: -138.78107934415706,
        },
        positionAbsolute: {
          x: 121,
          y: -139,
        },
      },
      {
        id: 'nodeId_YmbNTWlAdGP6o_7DuSvbf',
        data: {
          id: 'nodeId_YmbNTWlAdGP6o_7DuSvbf',
          name: 'changed name',
          type: 'WhileLoop',
          label: '',
          style: {
            width: 300,
            height: 300,
            textStyles: {
              zIndex: 10,
              fontSize: 14,
              fontAlign: 'center',
              fontColor: '#4D4D4D',
              fontFamily: 'Roboto',
              fontStyles: [],
            },
            borderColor: '#000',
            borderWidth: 1,
          },
          children: [],
          isExecuted: false,
          elementType: 'Node',
          isCollapsed: true,
          connectedNodes: [],
          incomingVariables: [],
          outgoingVariables: [],
        },
        type: 'WhileLoop',
        width: 145,
        height: 89,
        dragging: false,
        position: {
          x: -62.521831411227936,
          y: -58.89593315387488,
        },
        selected: true,
        positionAbsolute: {
          x: -62.521831411227936,
          y: -58.89593315387488,
        },
      },
    ],
    diagramEdges: [],
  },
};

module.exports = {
  DIAGRAM_ELEMENTS,
};
